### ISSUE TITLE
App crashing when calling disablePushNotifications()

### ISSUE THREAD

**Issue by tcruzibt** [realtime-framework/RealtimeStorage-Android#4]
Example:

StorageRef storageRef = new StorageRef(Config.APPKEY, Config.TOKEN, Config.PROJECT_ID, context);

TableRef tableRef = storageRef.table(Config.TABLE_NAME);

```
    tableRef.on(StorageRef.StorageEvent.UPDATE, new OnItemSnapshot() {
        @Override
        public void run(ItemSnapshot itemSnapshot) {

        }
    }, new OnError() {
        @Override
        public void run(Integer integer, String exception) {
            Log.e("Storage", "Exception :"+ exception);
        }
    }).disablePushNotifications();
```

**Comment by tcruzibt** [comment]
Further investigation shown the problem was on Ortc library on the class OrtcClient -> method isSubscribed(String channel)

**Comment by jparreira** [comment]
The underlying issue is really on the Realtime Messaging SDK.
See issue realtime-framework/RealtimeMessaging-Android#2
